### ISSUE TITLE
Feedback on week 9 project progress for CS2113T-W13-1

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-W13-1/main#158]
## Team progress for `v1.2`
* [x] Team PR created to the upstream repository with the title `[AY1920S1-CS2113T-W13-1] Contact List Pro`(:heavy_check_mark: well done!)
* Milestone `v1.2` properly managed:
   * [x] A suitable deadline 2019-10-15 set(:heavy_check_mark: well done!)
   * [x] Issues allocated to it https://github.com/AY1920S1-CS2113T-W13-1/main/pull/151 https://github.com/AY1920S1-CS2113T-W13-1/main/issues/135 https://github.com/AY1920S1-CS2113T-W13-1/main/issues/71 https://github.com/AY1920S1-CS2113T-W13-1/main/issues/67 https://github.com/AY1920S1-CS2113T-W13-1/main/issues/65 https://github.com/AY1920S1-CS2113T-W13-1/main/issues/63 https://github.com/AY1920S1-CS2113T-W13-1/main/issues/61 (:heavy_check_mark: well done!)
   * [x] All issues in this milestone are closed(:heavy_check_mark: well done!)
   * [x] Milestone explicitly closed(:heavy_check_mark: well done!)
   * [x] Code tagged as `v1.2`(:heavy_check_mark: well done!)
* Milestones setup:
   * [x] Milestone `v1.2` setup(:heavy_check_mark: well done!)
   * [x] Milestone `v1.3` setup(:heavy_check_mark: well done!)
   * [x] Milestone `v1.4` setup(:heavy_check_mark: well done!)
* Milestone v1.3 planned:
   * [ ] A suitable deadline 2019-10-29 set(:exclamation:)
   * [x] Issues allocated to it https://github.com/AY1920S1-CS2113T-W13-1/main/issues/102 https://github.com/AY1920S1-CS2113T-W13-1/main/issues/74 https://github.com/AY1920S1-CS2113T-W13-1/main/issues/73 https://github.com/AY1920S1-CS2113T-W13-1/main/issues/72 https://github.com/AY1920S1-CS2113T-W13-1/main/issues/64 (:heavy_check_mark: well done!)
## Individual progress of @danisheddie for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-W13-1/main/issues/67 https://github.com/AY1920S1-CS2113T-W13-1/main/issues/65 (:heavy_check_mark: well done!)
## Individual progress of @nottherealedmund for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-W13-1/main/issues/63 (:heavy_check_mark: well done!)
## Individual progress of @eujingsen for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-W13-1/main/issues/71 (:heavy_check_mark: well done!)
## Individual progress of @sfloydzy for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-W13-1/main/issues/135 https://github.com/AY1920S1-CS2113T-W13-1/main/issues/61 (:heavy_check_mark: well done!)

Tutor: @flxffy

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-10-16 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
